name: silverstripe-module-prep
description: preps a silverstripe module for being tested
inputs:
  silverstripe_version:
    description: the version to prep the module with
    default: '5.0'
runs:
  using: composite
  steps:
    - name: install dependencies
      shell: bash
      run: |
        git config --global --add safe.directory . &&\
        composer require --no-update silverstripe/recipe-cms:${{ inputs.silverstripe_version }} &&\
        composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile
