name: silverstripe-module-phpstan
description: preps and runs PHPStan for a silverstripe module
inputs:
  dir:
    description: where to execute phpstan
    required: true
  phpstan_binary:
    description: where to find the phpstan binary
    default: 'vendor/bin/phpstan'
  phpstan_config:
    description: where to find the phpstan config
    default: 'phpstan.neon'
  phpstan_bootstrap:
    description: where to find the bootstrap file
    default: 'vendor/syntro/silverstripe-phpstan/bootstrap.php'
  phpstan_level:
    description: what level to use for analysis
    default: '4'
runs:
  using: composite
  steps:
    - name: run phpstan
      shell: bash
      run: ${{ inputs.phpstan_binary }} analyse ${{ inputs.dir }} -c "${{ inputs.phpstan_config }}" --level ${{ inputs.phpstan_level }}
