name: Silverstripe Suite
# -----------------------------
# Silverstripe suite
# -----------------------------

on:
  workflow_call:
    inputs:
      # -----------------------------
      # configure eslint
      # -----------------------------
      eslint:
        description: runs the eslint check
        type: boolean
        default: false
      eslint_dir:
        # required: true
        type: string
      eslint_configfile:
        type: string
        default: .eslintrc
      eslint_ext:
        type: string
        default: js,jsx
      eslint_max-warnings:
        type: number
        default: 0
      eslint_node-ver:
        description: Which Node.js version to use for ESLint
        type: string
        default: 18.x
      # -----------------------------
      # configure stylelint
      # -----------------------------
      stylelint:
        description: runs the stylelint check
        type: boolean
        default: false
      stylelint_glob:
        # required: true
        type: string
      stylelint_max-warnings:
        type: number
        default: 0
      stylelint_node-ver:
        description: Which Node.js version to use for Stylelint
        type: string
        default: 18.x
      # -----------------------------
      # configure Jest
      # -----------------------------
      jest:
        description: runs Jest tests
        type: boolean
        default: false
      jest_node-ver:
        description: Which Node.js version to use for Jest
        type: string
        default: 18.x
      # -----------------------------
      # private access
      # -----------------------------
      uses_private_repos:
        description: if enabled, you can supply private keys to enable cloning private repositories !USE WITH CAUTION!
        type: boolean
        default: false
    secrets:
      uses_private_keys:
        description: The private keys to be loaded

jobs:
  eslint:
    if: ${{ inputs.eslint }}
    name: 🔧 ESLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: setup ssh agent
      if: ${{ inputs.uses_private_repos }}
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.uses_private_keys }}
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.eslint_node-ver }}
        registry-url: 'https://registry.npmjs.org'
    - name: Cache Node dependencies
      uses: actions/cache@v3.0.1
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Lint code
      run: |
        npx eslint \
          -c ${{ inputs.eslint_configfile }} \
          --ext="${{ inputs.eslint_ext }}" \
          --max-warnings="${{ inputs.eslint_max-warnings }}" \
          ${{ inputs.eslint_dir }}
  stylelint:
    if: ${{ inputs.stylelint }}
    name: 🖼 StyleLint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: setup ssh agent
      if: ${{ inputs.uses_private_repos }}
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.uses_private_keys }}
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.stylelint_node-ver }}
        registry-url: 'https://registry.npmjs.org'
    - name: Cache Node dependencies
      uses: actions/cache@v3.0.1
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Lint code
      run: |
        npx stylelint \
          --max-warnings="${{ inputs.stylelint_max-warnings }}" \
          ${{ inputs.stylelint_glob }}
  jest:
    if: ${{ inputs.jest }}
    name: 🃏 Jest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: setup ssh agent
      if: ${{ inputs.uses_private_repos }}
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.uses_private_keys }}
    - name: Install Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.jest_node-ver }}
        registry-url: 'https://registry.npmjs.org'
    - name: Cache Node dependencies
      uses: actions/cache@v3.0.1
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: npm install
    - name: Jest test
      run: npm test
