name: 🐳 Container

on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    branches:
      - master
    paths:
      - container/**
      - .github/workflows/internal_build_containers.yml

jobs:
  silverstripe:
    name: 🐘 Silverstripe Dev Apache
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push devenv
        uses: docker/build-push-action@v3
        with:
          context: container/silverstripe-dev
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/silverstripe-dev:${{ matrix.php_version }}-apache-buster
          target: devenv
      -
        name: Build and push devenv with cdr
        uses: docker/build-push-action@v3
        with:
          context: container/silverstripe-dev
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/silverstripe-dev:${{ matrix.php_version }}-apache-buster-chromedriver
          target: devenv-cdr
