name: Suite PHPStan
# -----------------------------
# PHPStan suite
# -----------------------------

on:
  workflow_call:
    inputs:
      dir:
        required: true
        type: string
      php_version:
        default: '8.1'
        type: string


jobs:
  phpstan:
    name: 🔺 PHPStan
    runs-on: ubuntu-latest
    container: syntrocontainer/silverstripe-dev:${{ inputs.php_version }}-apache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Composer Cache Directory
        id: composer-data
        run: |
          echo "::set-output name=dir::$(composer config --global data-dir)"
      - name: Cache Composer Cache and dependencies
        uses: actions/cache@v4.2.2
        with:
          path: |
            ${{ steps.composer-data.outputs.dir }}
            **/vendors
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer
      - name: Install Dependencies
        run: composer install
      - name: Run PHPStan
        run:  |
          vendor/bin/phpstan analyse ${{ inputs.dir }} \
            --memory-limit=1G \
            -c phpstan.neon \
            -a vendor/syntro/silverstripe-phpstan/bootstrap.php \
            --no-ansi \
            --level 4
